"""add is_active to user

Revision ID: 47b575dcb3d1
Revises: 545ae0ff7d04
Create Date: 2026-10-05 10:39:16.455514

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import geoalchemy2



# revision identifiers, used by Alembic.
revision: str = '47b575dcb3d1'
down_revision: Union[str, None] = '545ae0ff7d04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
