"""add_municipio

Revision ID: b83d10df8605
Revises:
Create Date: 2026-10-01 14:34:43.950497

"""

from typing import Sequence, Union

import geoalchemy2
import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b83d10df8605"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "municipios",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("nome", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("codigo_ibge", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "poligono",
            geoalchemy2.types.Geometry(
                srid=4326,
                dimension=2,
                spatial_index=False,
                from_text="ST_GeomFromEWKT",
                name="geometry",
            ),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_municipios_codigo_ibge"), "municipios", ["codigo_ibge"], unique=True
    )
    op.create_index(op.f("ix_municipios_nome"), "municipios", ["nome"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_municipios_nome"), table_name="municipios")
    op.drop_index(op.f("ix_municipios_codigo_ibge"), table_name="municipios")
    op.drop_table("municipios")
    # ### end Alembic commands ###
